### ISSUE TITLE
Added common JSCS [airbnb] for WS

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#19]
4/5 Используют WS, поэтому:
- поставим плагин https://www.jetbrains.com/webstorm/help/jscs.html
- конфиг будет в корне.

**Comment by ba2095** [comment]
5/5 теперь.
Уже ставлю. :smile:

**Comment by gaykov** [comment]
https://github.com/yandex-shri-minsk-2016/team-force/pull/21

**Comment by denisbalyko** [comment]
Closed in #21
