### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#24]
- Описать модели, схемы
- Основные взаимодействия

**Comment by ba2095** [comment]
Я заберу, у меня уже есть документ по этой теме.
Надо будет стараться его обновлять.

**Comment by denisbalyko** [comment]
Может выложить прямо сюда в wiki ? @ba2095

**Comment by gaykov** [comment]
@ba2095 постарайся закончить с этой задачей. Нужно обновить вики с нашим новым описанием моделей и взаимодействия (в общем)

**Comment by denisbalyko** [comment]
@ba2095 после сегодня у тебя остался листик с моделями. Его бы в wiki для всех выложить, было бы очень полезно.

**Comment by gaykov** [comment]
@denisbalyko хотя у нас ведь есть simple schema. Там есть описание всех полей с типами. Может вики лишнее?

**Comment by denisbalyko** [comment]
@gaykov иметь страничку с человеческим описанием все же стоит. Ты ведь в код метеора не каждый раз лазишь чтобы посмотреть как работает какой-то метод.

**Comment by gaykov** [comment]
@ba2095 вики отличное!
