### ISSUE TITLE
Pub/Sub Implementation

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#28]
Для этого старайтесь в темплейтах передавать не данные, а указатели. Тогда потом это будет формальностью.

**Comment by gaykov** [comment]
>Для этого старайтесь в темплейтах передавать не данные, а указатели. Тогда потом это будет формальностью.

можешь пояснить? не совсем понятно

**Comment by denisbalyko** [comment]
Значит так, если
collection.find({filters}).fetch() и передаешь это в шаблон, то данные выведутся и все хорошо,
НО
если на сервере произойдет обновление данных в collection на клиенте они не обновятся.
Чтобы обновление произошло передавать в шаблон нужно курсор collection.find({filters}).

Я видел что-то подобное в документации вместе со словами best practice, сейчас нашел вот что:

> When the database cursor is passed to #each, it will wire up all of the machinery to efficiently add and move DOM nodes as new results enter the query.

И статья которая описывает проблему, вероятно более понятным языком, чем я:

https://fogofcode.wordpress.com/2013/05/10/meteor-inconsistent-reactive-context-isolation-with-each/

**Comment by gaykov** [comment]
Надо это перенести куда-нибудь в документацию для нас

**Comment by denisbalyko** [comment]
@gaykov этот тикет ещё не закрыт, пока включен autopublish.
Так же это про то, что мы не будем передавать всю базу на клиента. А частичную доставку реализуем через встроенный механизм(паттерн) pub/sub.
Для этого роутинг кстати переписан был на IronRouter.
