### ISSUE TITLE
Company creating

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#30]
- [ ] Отдельные сущности для компании

- [ ] Пользователь при регистрации выбирает компанию, а не вводит её название

**Comment by denisbalyko** [comment]
@gaykov кстати в такой архитектуре у нас одна проблема, какую компанию должен выбрать первый человек если он не может ввести её? Или доступна регистрация без введения компании?

**Comment by ba2095** [comment]
@denisbalyko смотри в сторону регистрации в слаке(там то, чего мы хотим добиться, только тимы вместо компаний). :eyes: 
Для начала можно просто захардкодить список компаний(2-3), затем добавим регистрацию компаний. :computer:

**Comment by denisbalyko** [comment]
Мне кажется это неким оверхедом.

Да поле у всех дублируется, да его можно ввести неверно (допустить описку).
Но это не требует дополнительно коллекции, не требует дополнительного кода, не требует снова переписывать регистрацию (кстати там ещё тот костыль придется сделать).

И не совсем понимаю зачем такое внимание уделять компаниям.
Сортирующее поле это более чем достаточно, на мой взгляд, дать возможность его отредактировать в случае описки гораздо проще, чем выдумывать регистрацию компании.

**Comment by gaykov** [comment]
Мы не сможем корректно сортировать по названию компании. 

1. Во первых, это будет строка с пробелами и делать по таким запросам селекты - не быстро. 
2. Во вторых, как я говорил: "ООО Яндекс", "яндекс" и " yandex" - будет тремя разными компаниями
3. У каждого пользователя из одной компании мы будем храниьт одну и ту же информацию: адрес и название компании. Для чего?
4. В пане UX намного лучше не заставлять пользователя вводить название и адрес в надежне не ошибиться, а дать ему выбрать из списка.
5. Если мы перейдем к архитектура как у слэка (с поддоменами для компаний), то выбор будет очевиден.
6. Кода писать не много нужно будет.

>Компромиссным решением, думаю, будет сделать автокомплит при вводе компании.

В нашем случае это то же самое, что и выбор из списка.

Может быть тогда так. Автокомплит посказывает уже существущие компании, если компании нет, то появляется дополнительное поле для ввода адреса и создается компания.

Что вы думаете?

**Comment by denisbalyko** [comment]
Мы отказались от админки товаров впользу автопарсера, чтобы написать админку для компаний.
Сейчас я не представляю как это будет выглядеть и работать.
Поэтому если кто-то ещё подтвердит и возьмется реализовать, то ок.
Но все же я думаю у нас не столько времени, чтоб распыляться на такие задачи.

**Comment by denisbalyko** [comment]
Ещё одно компромиссное решение:
 - сделать коллекцию Company
 - после регистрации пользователя писать туда поле user.profile.company
Профит:
- не надо делать поиск по полю.
- всегда есть под рукой список уникальных компаний.
- автокомплит.

**Comment by gaykov** [comment]
Да, примерно это я и предлагал

>Может быть тогда так. Автокомплит посказывает уже существущие компании, если компании нет, то появляется дополнительное поле для ввода адреса и создается компания.

**Comment by denisbalyko** [comment]
@gaykov предлагаю ещё одно простое решение.
Если компания найдена то появляется :white_check_mark: а если нет то "вы первый в этой компании" или "будет создана компания"

**Comment by gaykov** [comment]
done @denisbalyko
