### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#32]
Система оповещений пользователя.
Все его действия могут храниться в истории.
Например:
- Вы создали пул с заказом на сумму 300,000 руб.
- К вашему пулу присоединился %username% и добавил заказ 153,000 руб.
- Пользователь %username% приглашает вас присоединиться к пулу.
- Ваш пул должен быть доставлен через час, пора собирать деньги.

В последствии эту систему расширить до нотификации в браузере. Это одна из доп фич написаных на листике.

Нужно ли это? На реализацию мне нужно 4 часа.

**Comment by gaykov** [comment]
Да, можно будет сделать, но не сейчас.

Для реализации советую посмотреть на https://onesignal.com/

**Comment by denisbalyko** [comment]
@gaykov оставлю тогда в тикетах, ели останется время или будет настрой, может запилим.

**Comment by denisbalyko** [comment]
Wow крутой сервис. Но это скорее для доп. фичи, а я изначально завел разговор про подоснову в виде уведомлений. Сейчас у нас все работает просто как переключалка. И даже не знаешь успешно завершено действие или нет.
Короче есть у меня пару ясных мыслей в реализации такой штуки. Поэтому отложим на неделю другую.

**Comment by denisbalyko** [comment]
Задача выполнена. Про возможное развитие потом создадим отдельный тикет.

**Comment by denisbalyko** [comment]
Feed - без него нельзя)
