### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#33]
Не могу найти нормальный способ тестирования метеор приложений. Нужно, видимо, брать какие-то модульные тесты. У кого какие идеи есть? jest, mocha?

**Comment by denisbalyko** [comment]
Я листал документацию видел phantomjs и mocha проскакивали. Завтра пересмотрю снова эту часть.

**Comment by denisbalyko** [comment]
https://atmospherejs.com/anti/gagarin
https://meteor-testing.readme.io/
https://chimp.readme.io/docs/getting-started-with-meteor-cucumber

**Comment by gaykov** [comment]
http://guide.meteor.com/testing.html

**Comment by denisbalyko** [comment]
По запросам находится velocity, как очень популярная штука. И у него есть velocity-coverage.
http://g00glen00b.be/unit-testing-meteor-applications-with-velocity-jasmine-and-sinon-js/
Наверх него можно накрутить самые популярные тестовые фреймворки.
Мы только юнит тестами ограничимся?

**Comment by gaykov** [comment]
Сделал базу для тестирования, сейчас нужно будет покрывать тестами весь новый код
