### ISSUE TITLE
Auto change pool state

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#60]
По истечении времени нужно автоматически изменять состояние заказа и переводить его в другое состояние

**Comment by ba2095** [comment]
Делается вместе с #58 
По моему нам должно подойти: [Later.js](http://bunkat.github.io/later/)

**Comment by denisbalyko** [comment]
#58 для этого не обязательно. 
В поле уже стоит дата, от неё и нужно танцевать. Как она туда попадет решат в #58.
