### ISSUE TITLE
Bug: Append item to order

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#64]
Создает новый вообще шикарно.
Но не добавляет товар в ордер, вероятно вопрос в мерже или инкременте count.

**Comment by denisbalyko** [comment]
Вот это, кстати, нужно тестами покрыть (метод findOrInsert), чтобы не возвращаться постоянно.
Структура уже меняться не будет.

**Comment by gaykov** [comment]
@denisbalyko ты имеешь ввиду добавление одинаковых товаров?

**Comment by denisbalyko** [comment]
@gaykov да, количество не добавляет.
Если один и тот же человек добавляет товар 2 раза.
