### ISSUE TITLE
Tests coverage and separate logic

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#69]
Нужно покрыть тестами уже существующий код и разделить логику работы.

- [x] Items collection
- [x] Orders colleection
- [x] Pools collection

**Comment by denisbalyko** [comment]
Нужно ли нам тестить view.js ? - Мы можем уйти от этого если часть функционала инкапсулировать внутри * collection.

Может поставим Velocity-Coverage? Чтобы наглядно видеть чего ещё можно протестить.

**Comment by gaykov** [comment]
>Нужно ли нам тестить view.js ? - Мы можем уйти от этого если часть функционала инкапсулировать внутри * collection.

Наверное, стоит пойти по второму пути. Так нам будет намного проще, потому что коллекции - это классы и их модульными тестами намного легче покрывать.

>Может поставим Velocity-Coverage? Чтобы наглядно видеть чего ещё можно протестить.

Мы ведь не используем Velocity для тестирования. Нам подойдет их coverage? Если нет, то можно посмотреть в сторону Istanbul (https://gotwarlost.github.io/istanbul/)

**Comment by gaykov** [comment]
#89
