### ISSUE TITLE
Company input

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#71]
- [x] Подсказка появляется только во время ввода и пропадает, когда компанию ввел. Нужно, чтобы она оставалась постоянно.
- [x] Автокомплит
- [x] Подтягивать адрес из компании, если она уже существует

**Comment by denisbalyko** [comment]
Вообще подсказка была для теста.
Автокомплит (#90)
Адрес у нас хранится у каждого пользователя (вернее не адрес а координаты телефон или что он туда укажет)
