### ISSUE TITLE
Order/Pool fields

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#73]
- [x] Fix orders
- [x] Fix Pools

Ещё нужны поля 
- order.isPaid - оплачен ли заказ == вернули ли долг?
- pool.address - место откуда потом можно забрать свою еду:)

**Comment by denisbalyko** [comment]
В Pool ещё нужно поля
- minDelivery - минимальный заказ.
- costDelivery - сколько стоит доставка.
- freeDelivery - от сколька доставка бесплатная.
Для чего это нужно.
Во-первых чтобы знать сколько ещё нужно до того чтобы вообще начали доставлять, ради стаканчика пепси никто не поедет.
Во-вторых чтобы разделить стоимость доставки на равные части если все же доставка оказалась платной.

**Comment by gaykov** [comment]
>В Pool ещё нужно поля

Тоскать одинаковые поля ко всем объектам в коллекции - идея так себе, учитывая, что у нас есть ключ, по которому их можно достать
