### ISSUE TITLE
Pool history miss-owned

### ISSUE THREAD

**Issue by ba2095** [yandex-shri-minsk-2016/team-force#74]
Проблема:
В версии 0.3 создаем пользователя.
Логинимся и создаем пул + заказ.
В истории получаем наш пул и заказ в нем. ( c `email for: undefined` :exclamation: ).
Разлогиниваемся.
Регистрируем нового пользователя(можно даже из другой компании) и заходим от его имени.
Видим ту же историю, что и предыдущий залогиненный юзер 1 в 1:exclamation:
PS: Кэш браузера отключен.
PPS: Логин от второго пользователя в Private Window не показывает чужую историю. (Предположительно, работает ок)

**Comment by denisbalyko** [comment]
Я вкурсе в чем дело. Могу забрать.

**Comment by gaykov** [comment]
@denisbalyko расскажи

**Comment by denisbalyko** [comment]
https://github.com/yandex-shri-minsk-2016/team-force/blob/master/imports/ui/components/history/history.js#L6-L7
Вот тут нужно посмотреть на userId() мне кажется тут и баг.

**Comment by gaykov** [comment]
@denisbalyko ну да, я в слэке ту же идею высказал. Забирай)

**Comment by denisbalyko** [comment]
Перепроверил. Все работает хорошо.
Если логиниться быстро и перелогиниватся то бывает что остаются старые, но это все в погрешности синхронизации минимонги.
После того как сделается pub/sub этого не будет.
Сейчас мы всю базу таскаем на клиент после каждой перезагрузки страницы поэтому она долго так соображает.
