### ISSUE TITLE
Add empty Item

### ISSUE THREAD

**Issue by denisbalyko** [yandex-shri-minsk-2016/team-force#75]
- Если ссылка не сработала, дать возможность добавления товара в ордер в ручном режиме. Показать поля пустыми.
- При добавлении товара показывать ниже доступные магазины/сайты и пример ссылки.

**Comment by gaykov** [comment]
Сейчас у нас в пуле есть поле магазина. Там лежит ссылка. Если полльзователь вставил ссылку на другой домен не проихойдет вообще ничего. Если парсер вернет пустые поля, то создается пустая форма. То есть все как надо сейчас работает.
