### ISSUE TITLE
Pool create

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#76]
Переделать (доделать) создание пула

- [x] Интегрировать DateTimePicker
- [x] Добавить возможность выбора магазина

**Comment by denisbalyko** [comment]
У парсера появится статический метод Parser.getShops() - выбор магазина от него делать.

**Comment by gaykov** [comment]
@denisbalyko еще нужен метод getShopInfo(), который будет возвращать поля вроде `minOrder`

**Comment by denisbalyko** [comment]
@gaykov все проще, в конструкторе у нас появился shop который имеет все свойства магазина.

**Comment by gaykov** [comment]
#84
