### ISSUE TITLE
Google/Facebook login

### ISSUE THREAD

**Issue by gaykov** [yandex-shri-minsk-2016/team-force#93]
Делается в три шага

http://meteor.hromnik.com/blog/login-with-facebook-twitter-and-google-in-meteor

**Comment by denisbalyko** [comment]
Стоп стоп стоп. Я может лучше напишу Oauth через яндекс.паспорт? Вроде беседа такая была;

**Comment by denisbalyko** [comment]
Просто к этому нужно ещё и редактирование личного кабинета.
Нужно посмотреть доку какие параметры возвращает их Oauth (и вроде фейсбук не отдает емейл).

Проблема такая если чел залогинен, но у него не указана компания и адрес то нужно его посылать на редактирование данных.

**Comment by gaykov** [comment]
>Я может лучше напишу Oauth через яндекс.паспорт?

зачем?

>(и вроде фейсбук не отдает емейл)

он и не нужен

>Проблема такая если чел залогинен, но у него не указана компания и адрес то нужно его посылать на редактирование данных.

да, нужно делать страницу

**Comment by denisbalyko** [comment]
Про _зачем?_ нужно обсудить с Сергеем. Если это не нужно, то да на это не будем тратить время.

depend #96

**Comment by gaykov** [comment]
Мы ведь спрашивали, таких условий нет. Пусть пока будет facebook/google (или только гугл)

**Comment by gaykov** [comment]
@denisbalyko верни мою задачу)

**Comment by denisbalyko** [comment]
@gaykov ок ок) я регистрацию переделывать буду, так вот думал сразу захвачу, мало ли как оно там создает пользователя по-другому.
